### ISSUE TITLE
Incorrect order of media quieries

### ISSUE THREAD

**Issue by novus57** [cssinjs/jss#391] opened 2016-12-22 09:54 UTC
I get incorrect order of media queries (max-width). It should go from middle to small but it has inverse order. Thanks for help.
Input: 
```
  heading: {
    position: 'relative',

    margin: '0 0 40px 0',
    padding: '20px 0 20px',

    color: '#fff',
    fontFamily: 'Prompt',
    fontSize: 24,
    fontWeight: 400,
    lineHeight: 1.67,

    '&::before': {
      content: '""',
      position: 'absolute',
      bottom: 0,
      left: 0,

      width: 100,
      height: 1,

      backgroundColor: '#808080',
    },

    [`@media (max-width: ${middle}px)`]: {
      margin: '0 0 30px 0',
      padding: '15px 0 15px',

      fontSize: 20,
    },

    [`@media (max-width: ${small}px)`]: {
      margin: '0 0 20px 0',
      padding: '10px 0 10px',
    },
  },
```
Output: 
```
@media (max-width: 600px) {
  .container-1284544947 {
    flex-direction: column;
  }
  .heading-1760943947 {
    margin: 0 0 20px 0;
    padding: 10px 0 10px;
  }
}
@media (max-width: 960px) {
  .heading-1760943947 {
    margin: 0 0 30px 0;
    padding: 15px 0 15px;
    font-size: 20px;
  }
  .navItem-3283730875 {
    font-size: 14px;
  }
}
```

**Comment by kof** [comment] 2016-12-22 09:57
Looks like a bug.

**Comment by kof** [comment] 2016-12-22 09:58
Which jss version and jss-nested version are you using?

**Comment by novus57** [comment] 2016-12-22 10:01
Yes, it was an order of properties problem. If the first property has media query of small so it will be first.
```
  container: {
    display: 'flex',
    justifyContent: 'space-between',
    flexGrow: 1,
    boxSizing: 'border-box',
    maxWidth: 1440,
    padding: '0 15px 0',

    [`@media (max-width: ${small}px)`]: {
      flexDirection: 'column',
    },
  },

  heading: {
    position: 'relative',

    margin: '0 0 40px 0',
    padding: '20px 0 20px',

    color: '#fff',
    fontFamily: 'Prompt',
    fontSize: 24,
    fontWeight: 400,
    lineHeight: 1.67,

    '&::before': {
      content: '""',
      position: 'absolute',
      bottom: 0,
      left: 0,

      width: 100,
      height: 1,

      backgroundColor: '#808080',
    },

    [`@media (max-width: ${middle}px)`]: {
      margin: '0 0 30px 0',
      padding: '15px 0 15px',

      fontSize: 20,
    },

    [`@media (max-width: ${small}px)`]: {
      margin: '0 0 20px 0',
      padding: '10px 0 10px',
    },
  },
```

**Comment by novus57** [comment] 2016-12-22 10:03
Version - 5.0.0

**Comment by kof** [comment] 2016-12-22 10:22
Are you using jss-nested directly or jss-default-preset? which version?

**Comment by kof** [comment] 2016-12-23 14:40
So the actual reason for this order is that your media query in the second rule was merged with the same media rule from the first rule.

**Comment by kof** [comment] 2016-12-26 15:41
It was actually a feature, which turns out in this case to be a specificity problem.

**Comment by kof** [comment] 2016-12-26 15:43
cc @johann-sonntagbauer

**Comment by kof** [comment] 2016-12-26 16:31
Oh the problem is that we actually map nested at-rules to the sheet-level at-rules … so we have no other choice but to merge them, otherwise they will override each other.

**Comment by johann-sonntagbauer** [comment] 2016-12-26 20:13
@kof yes, at rules are lifted to the sheet level and merged. I am not sure if the order of the nested rule should be applied to the sheet level rule. As you mentioned the outcome is unpredictable.

**Comment by kof** [comment] 2016-12-26 20:18
Maybe we need to find a way to not merge them at all and keep them exactly in the order they are defined?

**Comment by johann-sonntagbauer** [comment] 2016-12-26 20:27
after some thoughts - yes that would be the only possibility. The result should be not to combine at rules (or maybe only compatible ones) 
The simplest solution would be to wrap each nested rule into its own sheet level at rule.

**Comment by johann-sonntagbauer** [comment] 2016-12-26 20:28
should I take a look at this one tomorrow afternoon?

**Comment by kof** [comment] 2016-12-26 20:30
That would be great!

**Comment by johann-sonntagbauer** [comment] 2016-12-27 19:48
Started the investigation. Its kind of tricky to get the ordering right. Need some more time to dig deeper. Main Problem so far is the correct setup of the options object. Somehow some conditional rules get lost and I have to debug deeper to find all edge cases.

**Comment by johann-sonntagbauer** [comment] 2016-12-30 17:50
https://github.com/cssinjs/jss-nested/pull/19
Added the propoced fix. No rule merging is applied any longer and the ordering is preserved by passing the options.

**Comment by kof** [comment] 2016-12-31 19:49
fixed and released, thanks @johann-sonntagbauer and @novus57

**Closed by kof** 2016-12-31 19:49 UTC
Labels: bug

**Comment by denyo** [comment] 2021-03-31 11:44
We came across a similar issue today with multiple media queries defined both at the root level but also nested. 
It seems like `jss-plugin-nested` sorts media queries by string and not by number, therefore, a `1000px` media query is before a `768px` media query.
We ended up using https://www.npmjs.com/package/jss-plugin-sort-css-media-queries for now.

**Comment by kof** [comment] 2021-04-01 08:09
@denyo this issue has been closed and marked as fixed, I suggest to create a new issue with a reproduction. It might be even a separate problem.
