### ISSUE TITLE
Dynamic value in reused component gives warning on server in nextjs

### ISSUE THREAD

**Issue by BenjaminWFox-Lumedic** [cssinjs/jss#1400] opened 2020-09-30 21:54 UTC
__Expected behavior:__
A component that works as expected where there is only one on the page should also work as expected, without warnings, when there are multiple on the page.

__Describe the bug:__
I have a component that uses a dynamic value. When I use it on any given page by itself it works as expected - no warnings.

When I use 2 or more of this component, however, I receive a warning on the server:
- `Warning: [JSS] Rule is not linked. Missing sheet option "link: true".`

This warning appears once for every instance of the component used beyond the first.

Hopefully this is not my missing something obvious, apologies if so.

__Codesandbox link:__ 
https://codesandbox.io/s/jss-warning-rule-is-not-linked-rz1d5?file=/pages/error.js

^ You will be able to see the warning when multiple instances of `MyComponent` are present, see the page `error.js` - you can see that there are no warnings when only a single instance of MyComponent is present, as in `index.js`

__Versions (please complete the following information):__
 - jss: (`react-jss`) 10.4.0
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: macOS
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by BenjaminWFox-Lumedic** [comment] 2020-11-06 15:57
Wanted to add an update here. I was looking into this again in a new context and it appears to actually be a regression introduced in https://github.com/cssinjs/jss/releases/tag/v10.0.1.

Per issue reported in https://github.com/cssinjs/jss/issues/1143 and fixed in https://github.com/cssinjs/jss/pull/1140 I would expect that using function rules in `createUseStyles` would not trigger the `Warning: [JSS] Rule is not linked. Missing sheet option "link: true".` on the server.

Using `react-jss@10.0.1` (or later, up to 10.4.0), when I include two of the same components that make use of function props, I receive warnings `Warning: [JSS] Rule is not linked. Missing sheet option "link: true".` on the server.

This does not happen using `react-jss@v10.0.0`

Additional codesandbox specifically on 10.0.1: https://codesandbox.io/s/condescending-hypatia-tstqz?file=/pages/index.js

**Comment by timsnadden** [comment] 2020-11-16 20:26
I believe that this is a duplicate of https://github.com/cssinjs/jss/issues/1277

**Closed** 2021-01-27 13:49 UTC
