### ISSUE TITLE
does't have any style propertys hint

### ISSUE THREAD

**Issue by Richard-Choooou** [cssinjs/jss#1227] opened 2019-10-31 04:28 UTC
__Expected behavior:__
![image](https://user-images.githubusercontent.com/23492006/67918842-fc8b3500-fbd8-11e9-9b53-b6296c8dce69.png)

![image](https://user-images.githubusercontent.com/23492006/67918961-74f1f600-fbd9-11e9-81de-7994fad060cb.png)

__Describe the bug:__
A clear and concise description of what happend instead of the expected behavior.

__Codesandbox link:__ 
Please create a codesandbox.io with the issue. Make it as minimal as possible as this will help us find the bug quicker.

__Versions (please complete the following information):__
 - jss: ^10.0.0
 - Browser [e.g. chrome, safari]:
 - OS [e.g. Windows, macOS]: macOS
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by chrisands** [comment] 2019-11-02 01:22
It is duplicate of issue #1199

**Comment by HenriBeck** [comment] 2019-11-02 11:49
Closing as this is a duplicate of #1199. I hope to get better typing support in #1218

**Closed by HenriBeck** 2019-11-02 11:49 UTC
