### ISSUE TITLE
`Can not insert an unsupported rule` when using react-jss with dynamic values on chrome

### ISSUE THREAD

**Issue by enisdenjo** [cssinjs/jss#1087] opened 2019-04-11 11:06 UTC
__Expected behavior:__
Using browser targeting CSS like: `.button-class::-moz-focus-inner {}` together with dynamic values `react-jss` should apply all rules on `chrome`.

__Describe the bug:__
When using browser targeting CSS like: `.button-class::-moz-focus-inner {}` together with dynamic values on `react-jss`, breaks when using `chrome`. The console reports `Warning: [JSS] Can not insert an unsupported rule...` and `chrome` does not apply the browser targeting rule nor **any** rules with dynamic values.

You can find the reproduced issue in the **Codesandbox** below.

When using:
```js
label: {
  fontSize: 16,
},
```
every rule is applied (including the `::-moz-focus-inner`).

However,  using:
```js
label: ({ fontSize }) => ({
  fontSize,
}),
```
`chrome` does not insert: the `::-moz-focus-inner` nor the `label` rule (or any other dynamically applied rule).

__Codesandbox link:__ 
https://codesandbox.io/s/m5mzmlk26y

__Versions:__
 - jss: `10.0.0-alpha.16`
 - react-jss: `10.0.0-alpha.16`
 - Browser [e.g. chrome, safari]: `chrome v73.0.3683.103`

**Comment by kof** [comment] 2019-04-11 19:04
Looks like the problem is that with insertRule API `::-moz-focus-inner` selector doesn't work and  the dynamic rule switches the sheet to use insertRule, making this fail a combination of those 2 things.

It worked in v8.6.1 because we used a separate style tag for dynamic rules and didn't switch static rules to use insertRule.

**Comment by enisdenjo** [comment] 2019-04-12 06:22
It works up until `react-jss v10.0.0-alpha.12`. I guess something from this PR: #1048 caused the regression.

**Comment by kof** [comment] 2019-04-12 16:50
Yes, this is where we switched to single style sheet for performance reasons.

**Comment by kof** [comment] 2019-04-12 16:53
`::-moz-focus-inner` is a firefox specific selector, I think we just need to make sure we don't fail other rules if one rule can't render, because in this case, that rule wouldn't do anything in chrome and others anyways, it should justs fail silently like CSS usually does in such cases.

**Comment by kof** [comment] 2019-06-12 12:43
Duplicate of #1122, is fixed will be released next in the alpha

**Closed by kof** 2019-06-12 12:43 UTC
Labels: bug
