### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by JonasRosenqvist** [cssinjs/jss#1472] opened 2021-03-21 09:38 UTC
I can't seem to find any actual documentation of the features of JSS. In particular, I don't know where the syntax is defined. Has it been copied from a pre-existing framework that I'm unfamiliar with? If so, it would be great if this could be clearly stated somewhere. 
I know it's claimed that the documentation can be found at https://cssinjs.org/, but I only find examples, showcases, installation guides etc. Examples of questions I have include: what does the "&" sign mean and how can it be used? When is the feature know as  `jss-expand` applicable? When it comes to keys with white-spaces, why are some converted to camleCase while others are but in quotation marks? What's the difference? Where is the API documentation that answers these questions?

**Comment by kof** [comment] 2021-03-21 09:41
The problem is that & syntax is implemented in a jss-plugin-nested syntax, core syntax is https://cssinjs.org/jss-syntax?v=v10.6.0

If you have an idea how to make this problem with docs go away, please propose

**Comment by kof** [comment] 2021-03-21 09:42
> When it comes to keys with white-spaces, why are some converted to camleCase while others are but in quotation marks?

That is just javascript restrictions, space can't be a key without quotes

**Comment by kof** [comment] 2021-03-21 09:50
Created a separate issue for learning the syntax in one place https://github.com/cssinjs/jss/issues/1473

**Comment by kof** [comment] 2021-03-21 09:50
Let me know if this issue doesn't cover everything you asked. We don't really want to cover javascript basics though.

**Comment by JonasRosenqvist** [comment] 2021-03-21 11:47
Thanks @kof ! I think that covers it.
 I had actually missed your first link (https://cssinjs.org/jss-syntax?v=v10.6.0) entirely. I obviously could have looked more carefully and found it, but I think it might be better to break out `Packages > JSS Core > API` and `Styles Syntax` and make it much more visible, possibly under _Introduction_. Here one might also mention that much more features are available as plugins, give a few examples, and link down to _Packages_.
It might also be worth keeping in mind that a lot of users don't actively chose jss. For example, I'm using the material [material-ui ](https://material-ui.com/) in a React project, which in turn is using jss with various plugins. I only found this this site after going looking for API documentation of what I originally thought was an internal material-ui feature. My point here is that some users (like me) don't even know what packages are being used before their intermediate framework doesn't make it clear.

**Comment by kof** [comment] 2021-03-21 11:50
If you like to contribute to that documentation problem, lets discuss the details in that issue referenced above, closing this one

**Closed by kof** 2021-03-21 11:50 UTC
