### ISSUE TITLE
[question] Is it possible to generate consistent classNames despite the order of rendering?

### ISSUE THREAD

**Issue by bungu** [cssinjs/jss#1058] opened 2019-03-13 14:29 UTC
In my project I have an issue with react and SSR. `ReactDOM.hydrate` updates only text content of the DOM element, but not attributes, so if classNames are different on client side, react will not change it.

For example, if JSS on server generates classname `MyComponent-key-0-2-10`, server return this HTML:

```html
<style>.MyComponent-key-0-2-10 {...}</style>
<div class="MyComponent-key-0-2-10" />
```
Then on client side JSS generates `MyComponent-key-0-2-25` and adds styles to the `<HEAD>`:

```html
<style>.MyComponent-key-0-2-25 {...}</style>
```

But react is not changing `<div class="MyComponent-key-0-2-10" />` to `<div class="MyComponent-key-0-2-25" />` on initial render. As I found out this behaviour was made intentional to force react to reuse as much as possible from server side render.

It seems that I have different classNames because some components are rendered on client side only, so the counter is inconsistent between server and client. But my app is pretty huge and it is nearly impossible to find which component was rendered just on client side. So I thought if it's possible to generate unique classNames based on styles object, maybe using hash function instead of counter (performance issues are out of the scope atm). If it's possible, we'll get the same classNames despite the order of rendering. My goal is to have className like `componentName-key-hash`.

I tried to use `createGenerateClassName` function, but it's calling before plugins execution, so the rule object is not filled with styles yet. Then I tried to add custom plugin at the end of the queue and calculate hash in `onProcessStyle` callback, but the rule is already have className at this point, and probably it's a bad idea to mutate rule and sheet objects here.

So, my question is, can we generate classNames this way? Is it even possible?

**Comment by kof** [comment] 2019-03-13 14:40
Please provide a codesandbox minimal example. You can fake it buy outputing an ssr like html/css first and then rehydrating from there.

**Comment by kof** [comment] 2019-03-13 14:48
The reason I ask for reproduction here is that it's not obvious how you managed to not rerender components which need a new class name, since your SSR and runtime rendering differs.

**Comment by kof** [comment] 2019-03-13 14:50
Using hashes is possible and all you need is createGenerateClassName, you will  not be able to use function values atm.

Also I assume you are using v9, we have v10 alpha, all fixes go into alpha.

**Comment by bungu** [comment] 2019-03-13 15:16
Example: https://codesandbox.io/s/5x56y2ypwn

> you will not be able to use function values atm

If I have styles like this:

```javascript
const style = {
  button: {
    color: ({ color = '#C00' }) => color,
  }
}
```

...hash for every object will be the same, because value is not calculated yet in the `createGenerateClassName`. That's why I tried to use plugin for this, because plugin at the end of the queue will return flat object with all values available. In `onProcessStyle` callback I can get hash even of "function values", because it is not function anymore.

**Comment by kof** [comment] 2019-03-13 15:18
@bungu yeah, this is currently "unsolved"

**Comment by bungu** [comment] 2019-03-13 15:28
So, if performance is not the issue, what should i do? Should I add method to `rule` object that generates classNames for it with hashing?

It's not possible to do it with `createGenerateClassName` and plugins, right?

**Comment by oliviertassinari** [comment] 2019-03-13 15:30
@bungu Even if you solve the class name issue, you should still have a problem, it's the tips of the iceberg. If you are rendering a component on the client and not on the server, it won't work properly. You should be able to quickly find the culprit with dichotomie, no matter how big your app is. Also, have a look at https://material-ui.com/utils/no-ssr/. It should solve your problem.

**Comment by HenriBeck** [comment] 2019-03-15 19:58
I will close this as the real solution is to render the same on the server as on the client.

**Comment by kof** [comment] 2019-03-15 19:59
Rehydration should be the same, but then one could render anything else.

**Closed by HenriBeck** 2019-03-15 19:58 UTC
Labels: needs reproduction
