### ISSUE TITLE
[jss-default-unit] Error if undefined or null property defined inside array

### ISSUE THREAD

**Issue by alebiavati** [cssinjs/jss#307] opened 2016-09-05 19:21 UTC
My JSS stylesheet:

```js
const accentColor = null;
const styles = {
    border: [[2, 'solid', accentColor]],
};
```

I get the following error:

```
Uncaught TypeError: Cannot read property 'constructor' of null at webpack:///~/jss-default-unit/lib/index.js:24:0
```

I think the border color in this case should simply be ignored instead of throwing.
I can a pull request for this if you agree.

**Comment by kof** [comment] 2016-09-05 19:50
I think your code is wrong ... can't reproduce.

**Comment by alebiavati** [comment] 2016-09-09 17:29
Hi, sorry for the delay.

Here is how to reproduce it using the first example in the JSS readme file:

```js
import jss from 'jss'
import defaultUnit from 'jss-default-unit'
import color from 'color'

// just using just jss-default-unit for this test instead of importing the preset
jss.use(defaultUnit())

const styles = {
  button: {
    padding: null,     // adding a null property
    fontSize: 12,
    '&:hover': {
      background: 'blue'
    }
  },
  ctaButton: {
    extend: 'button',
    '&:hover': {
      background: color('blue').darken(0.3).hexString()
    }
  },
  '@media (min-width: 1024px)': {
    button: {
      width: 200
    }
  }
}

const {classes} = jss.createStyleSheet(styles).attach()

document.body.innerHTML = `
  <button class="${classes.button}">Button</button>
  <button class="${classes.ctaButton}">CTA Button</button>
`
```

Again, I get this error at `jss-default-unit/lib/index.js:24`:

```
Uncaught TypeError: Cannot read property 'constructor' of null
```

Notice that the behaviour without using `jss-default-unit` would be to just ignore the `null` property.

**Comment by kof** [comment] 2016-09-09 17:34
Why would you want to use null?

**Comment by kof** [comment] 2016-09-09 19:09
Figured it makes sense as we also skip empty rules.

**Comment by alebiavati** [comment] 2016-09-09 19:11
For a multi-theme system. Putting it in the simplest terms I have a set of variables in an object and I'm passing it to a function that generates the styles object to pass to JSS.

Some of the variables might not be set in the input theme.

*Option 1:*

I could set default values inside my function but that would make the generated CSS bigger:

```
function getStyles(inputTheme) {
  theme = Object.assign({}, { padding: 'inherit' }, inputTheme}
  return {
    padding: theme.padding,
  };
}
```

*Option 2:*

This is just tedious:

```
function getStyles(theme) {
  return {
    ...(theme.padding ? { padding: theme.padding } : {})
  };
}
```

Instead I think JSS could just ignore the rules with undefined values.

**Comment by alebiavati** [comment] 2016-09-09 19:11
You beat me to it :)

**Comment by kof** [comment] 2016-09-09 19:20
fixed in both jss and js-default-unit and jss-preset-default.

Also feel free to start using jss-preset-default.

**Closed by kof** 2016-09-09 19:20 UTC
Labels: enhancement
