### ISSUE TITLE
[react-jss] stylesheet doesn't updates if `!important` is set

### ISSUE THREAD

**Issue by chrisands** [cssinjs/jss#1207] opened 2019-10-03 14:04 UTC
__Expected behavior:__
Stylesheet updates and color toggles with `!important`

__Describe the bug:__
The stylesheet doesn't update if `!important` is set. It starts the update if remove `!important`

__Codesandbox link:__ 
https://codesandbox.io/s/sleepy-curie-rkczo

__Versions (please complete the following information):__
 - jss: 10.0
 - Browser [e.g. chrome, safari]: firefox, chrome
 - OS [e.g. Windows, macOS]: macOS

**Comment by JairoDuarte** [comment] 2019-12-11 09:10
You'll need to use this syntax for !important:  `const color = active ? ['red', '!important'] : ['green', '!important'];
`
you can check  [here](https://github.com/cssinjs/jss/issues)

**Comment by kof** [comment] 2019-12-12 10:48
That's not the problem here @JairoDuarte, his syntax is fine, it seems to not update.

**Comment by kof** [comment] 2019-12-14 15:11
Seems like the problem is only reproducible when component that uses a function rule is a list item

**Comment by thomasgrivet** [comment] 2020-01-16 10:13
Can confirm the bug is still present, here's the link to a codesandbox: https://codesandbox.io/s/bold-https-k2ors?fontsize=14&hidenavigation=1&theme=dark

Will use the array syntax for now 👍

**Comment by kof** [comment] 2020-01-16 10:19
@thomasgrivet are you saying array syntax works in this case?

**Comment by thomasgrivet** [comment] 2020-01-16 10:28
> @thomasgrivet are you saying array syntax works in this case?

It does partly works.
I just realised that using arrays works well with some properties but not with others like fontSize.
You can take a look at a new codesandbox here: https://codesandbox.io/s/delicate-frost-coqtx?fontsize=14&hidenavigation=1&theme=dark

**Comment by kof** [comment] 2020-01-16 10:37
On a brief look your example also works with strings
```js
export const styles = {
  container: ({ variant }) => ({
    padding: 20,
    fontSize: '40px !important',
    backgroundColor: `blue !important`
  })
};

```

**Comment by thomasgrivet** [comment] 2020-01-16 10:43
Trying it but it doesn't works, can you provide a working codesandbox so I can differentiate your code and mine?

Here is a codesandbox using strings:
https://codesandbox.io/s/delicate-frost-coqtx?fontsize=14&hidenavigation=1&theme=dark

**Comment by ernestostifano** [comment] 2020-05-04 22:04
@kof The problem is not with `react-jss`. I'm currently having the same issue using a custom JSS instance and manually calling `styleSheet.update`.

**Comment by David-Finkelstein** [comment] 2021-01-03 09:48
@kof any update?

**Comment by IIIristraM** [comment] 2021-05-16 21:12
It looks like [this](https://github.com/cssinjs/jss/blob/26b9919193490abfc57cda7fa3278b33ac1ecd48/packages/jss/src/DomRenderer.js#L80) row can't update CSS rule if value contains `!important`, so code like this doesn't work

```
display: props => `${props.display}` !important
...
cssRule.style.setProperty('display', 'flex  !important') // nothing happens
```

but code like this will work because it leads to [this](https://github.com/cssinjs/jss/blob/26b9919193490abfc57cda7fa3278b33ac1ecd48/packages/jss/src/DomRenderer.js#L71) row, which updates the rule correctly.

```
display: props => [props.display, '!important']
..
cssRule.style.setProperty('display', 'flex', 'important') // rule is updated
```

As was mentions before by @thomasgrivet , this way doesn't fix problem for all CSS properties. One reason I found is [here](https://github.com/cssinjs/jss/blob/master/packages/jss-plugin-vendor-prefixer/src/index.js#L49). `supportedValue` from `css-vendor` leads arrays where first item started with digits to be converted into string, ie `[5px, '!important'] -> '5px !important'`, which is invalid as I mentioned at the beginning. But for example `display` property will work well, cause it contains no digits ie `[flex, '!important'] -> [flex, '!important']`

The root of this behavior is [here](https://github.com/cssinjs/css-vendor/blob/master/src/supported-value.js#L52), that's how `parseInt` works, ie `parseInt('5px') -> 5`.

**Comment by IIIristraM** [comment] 2021-07-01 18:52
@kof ping

**Comment by kof** [comment] 2021-07-02 00:52
When value contains a number, prefixer bails out. So the problem  could be in the prefixer or we need to also have a similar logic for strings which have important and separate the important out as a separate argument like [we do](https://github.com/cssinjs/jss/blob/master/packages/jss/src/DomRenderer.js#L70) for arrays

**Comment by IIIristraM** [comment] 2021-07-07 07:44
So, would it be fixed, or repository is no longer maintained ? `important` is a common css feature, and as far as this bug is not fixed, jss not covers even css specification. Bug is opened for two years and it's not the only one critical bug in jss that's not fixed for a long time.

**Comment by kof** [comment] 2021-07-07 09:24
Open Source works this way: everyone who is using the product contributes to it and fixes problems they have. Since I never use "important", I never had this problem. So saying it's not maintained is wrong, but also I don't work on it full time to implement everything community wants. 

I can help implementing a fix by reviewing a PR and guiding it in a better direction.

**Comment by IIIristraM** [comment] 2021-07-07 10:09
Well, it's ok, could you make a comment regarding this https://github.com/cssinjs/jss/issues/1207#issuecomment-841878405.

Does this line work as intended https://github.com/cssinjs/css-vendor/blob/master/src/supported-value.js#L52 (`parseInt('5px') -> 5`) ? 

This function is used by perfixer here https://github.com/cssinjs/jss/blob/master/packages/jss-plugin-vendor-prefixer/src/index.js#L49 and looks like `parseInt` is the root of the bug

Does it make sence, or I'm looking in a wrong direction ?

**Comment by kof** [comment] 2021-07-07 14:23
> Does this line work as intended https://github.com/cssinjs/css-vendor/blob/master/src/supported-value.js#L52 (parseInt('5px') -> 5) ?

That line is there to avoid feature testing values like 5px for support, because we are only interested in values which could be actually vendor prefixed. So it just bails when a string has a numeric value and can't be vendor prefixed. It's just an accident that bailing out of vendor prefixing made some other value actually work, so yeah this line is fine relative to this issue.

>  it should be replaced with some function that would convert only numbers instead of any string started with number.

it wouldn't account for values which are strings, e.g.: margin:'5px' or margin: '5px 5px'

**Comment by kof** [comment] 2021-07-07 14:28
It seems we need to fix it https://github.com/cssinjs/jss/blob/master/packages/jss/src/DomRenderer.js#L70 by checking if the value has an !important at the end and passing it as a 3rd argument to setProperty separately.

**Comment by behnammodi** [comment] 2022-04-24 02:06
> It seems we need to fix it in https://github.com/cssinjs/jss/blob/master/packages/jss/src/DomRenderer.js#L75 by checking if the value has an !important at the end and passing it as a 3rd argument to setProperty separately.

This PR https://github.com/cssinjs/jss/pull/1612 will be fixed it

**Comment by kof** [comment] 2022-04-24 22:30
released https://github.com/cssinjs/jss/releases/tag/v10.9.1-alpha.2

**Closed by kof** 2022-04-24 22:30 UTC
Labels: bug, important, help wanted
