### ISSUE TITLE
[react-jss] Object returned from useStyles should be referentially consistent if values have not changed.

### ISSUE THREAD

**Issue by justmatt** [cssinjs/jss#1416] opened 2020-10-30 16:37 UTC
__Problem__
Causing unnecessary render of child components receiving prop containing return value of useStyles

__Expected behavior:__
If styles object provided to createUseStyles has not changed, object returned from useStyles should be referentially consistent.

__Describe the bug:__
When styles object provided to createUseStyles has not changed, object returned from useStyles is not referentially consistent.

__Codesandbox link:__ 
https://codesandbox.io/s/interesting-drake-wnq70

__Versions (please complete the following information):__
 - jss: 10.4
 - Browser [e.g. chrome, safari]: Chrome 85.0.4813.83 (32-bit)
 - OS [e.g. Windows, macOS]: Windows

**Comment by kof** [comment] 2021-01-27 12:28
I agree, it's about the data argument `useStyles(data)`, if the same object has been passed or none at all, we should be able to return same classes object.

If a new data object reference has been passed, it's not trivial anymore to detect a change, because it's being passed to users function values/rules and we would have to identify changes from every such update, but for the same data reference, it should be easy.

**Comment by kof** [comment] 2021-01-27 12:29
@justmatt if you are interested in fixing it let me know, otherwise it's gonna wait for someone who is interested enough.

**Comment by kof** [comment] 2021-01-27 12:35
Btw. this is a duplicate of https://github.com/cssinjs/jss/issues/1347

What is the use case for referential equality? You pass down to the element the class itself, not the classes object, e.g. <div className={classes.item}/> This doesn't make it rerender if the class string is the same.

**Closed by kof** 2021-01-27 12:35 UTC
Labels: enhancement
