### ISSUE TITLE
Jest snapshot serializer

### ISSUE THREAD

**Issue by DanielFerrariR** [cssinjs/jss#1275] opened 2020-02-02 01:40 UTC
> So far, i didnt found any solution to expose material ui classes like jest-emotion and jest-styled-components do.
> 
> Example:
> I'm using material-ui/system solution for padding and margin in almost all my components, but would be nice if I could see the difference in the snapshots. So far, if I add a padding to a Box, the class stay the same and the test passes and thats no helpful at all.
> 
> Using: material-ui (core, system), jest, testing-library/react

So, I posted it on Material UI issues track and got a reply that i should ask for it here. I searched in the issues of both libs and, so far, didn't found any solution for my problem.

So far, I exposed all classes of my component with a StylesheetRegister, but that was a mess and not helpful at all for debugging.

**Comment by bartlomiejzuber** [comment] 2020-02-02 13:24
Hey, I have the similar issue and I've also thought that might be mui issue.

https://github.com/mui-org/material-ui/issues/19048

Box styles are inserted via .insertRule API hence the issue.

**Comment by kof** [comment] 2021-01-27 14:13
Yeah, seems like a duplicate of https://github.com/cssinjs/jss/issues/804, someone should create a this package

**Closed by kof** 2021-01-27 14:13 UTC
