### ISSUE TITLE
Styles created multiple times when using function values and css selectors in createUseStyles

### ISSUE THREAD

**Issue by jbojcic1** [cssinjs/jss#1181] opened 2019-08-24 21:10 UTC
__Expected behavior:__
Duplicate styles shouldn't be created.

__Describe the bug:__
On every component render, in which useStyles prop changes, new duplicate styles are created. I've managed to reproduce the bug in Codesandbox. To see it:

1. Open codesandbox link from below
2. Inspect red text element and see styles applied
3. Click on button few times to cause component re-render
4. Inspect some another element on the page and the red text again.
5. Notice duplicate styles

The styles are duplicated only for elements styled with css selector. If you check styles on the element with container class, you'll see there is no duplication there.

__Codesandbox link:__ 
https://codesandbox.io/s/react-jss-playground-kkso6

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.24

Screenshot:

![Screen Shot 2019-08-24 at 11 09 29 PM](https://user-images.githubusercontent.com/10374826/63642736-4250ec00-c6c4-11e9-8b51-56e3030f0c72.png)

**Comment by HenriBeck** [comment] 2019-08-25 11:08
This would fix the issue:
```
const useStyles = createUseStyles({
  root: {
    background: "linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)",
    border: 0,
    borderRadius: 3,
    boxShadow: "0 3px 5px 2px rgba(255, 105, 135, .3)",
    color: "white",
    height: 48,
    padding: "0 30px"
  },
  container: {
    marginLeft: ({ flag }) => flag ? 30 : 0,
    "& > div": {
      color: "red",
      marginTop: 24
    }
  }
});
```

Keeping this open as this is not a proper solution.

**Comment by jbojcic1** [comment] 2019-08-25 11:16
Hm, I didn't know function can be used for specific css properties inside the class. Thx.

**Comment by jbojcic1** [comment] 2019-08-25 11:19
Still it doesn't solve my original issue where I need to build css properties inside the class function dynamically.

**Comment by yhaskell** [comment] 2020-01-27 07:54
I see that this wasn't touched for almost half a year now.

Would you accept PRs?

**Comment by kof** [comment] 2020-01-27 10:45
Was fixed in 10.0.3, please check and reopen if I am wrong.

**Closed by kof** 2020-01-27 10:45 UTC
Labels: bug

**Comment by sergnek** [comment] 2020-04-11 13:14
> Was fixed in 10.0.3, please check and reopen if I am wrong.
<img width="2792" alt="Снимок экрана 2020-04-11 в 16 06 02" src="https://user-images.githubusercontent.com/21196459/79044719-7820f180-7c0f-11ea-9134-42442b8c84af.png">

I think bug is still there with version 10.1.1
you can reproduce it here https://codesandbox.io/s/react-jss-playground-7ftrs?file=/index.js
it's just the same sandbox as in the first comment of this issue, but with new version of react-jss (10.1.1)

**Comment by sergnek** [comment] 2020-04-20 12:19
@kof , @HenriBeck  can you take a look at my comment above please

**Comment by LAKnoKAL** [comment] 2020-07-21 09:51
@kof "react-jss": "^10.3.0", for me it's the same as for @sergnek

**Comment by robertofabrizi** [comment] 2020-10-08 07:11
Same issue here

**Comment by ccpu** [comment] 2020-11-04 12:09
same here

**Comment by soul-codes** [comment] 2021-01-14 08:38
Here's a minimal example in 10.5.0: https://codesandbox.io/s/react-jss-playground-forked-zpijb, each instance of the call to the hook produces a new class. 


Note that in the example below, the style object is even referentially identical, but that doesn't seem to matter.
![Annotation 2021-01-14 153521](https://user-images.githubusercontent.com/40335030/104565072-4ea16480-567e-11eb-8d40-cee3109499bc.png)

The example is contrived as in this particular case the function form isn't needed, but it does demonstrate the bug nevertheless.

![Annotation 2021-01-14 153520](https://user-images.githubusercontent.com/40335030/104565067-4d703780-567e-11eb-81a7-fd490b4dc822.png)

**Comment by IIIristraM** [comment] 2021-05-14 14:46
^up

this behavior significantly decrease performance, generally it leads to necessity of rewriting all data sets like tables without such components, otherwise hundreds of classes are created

**Comment by kof** [comment] 2021-05-14 18:02
At the core of this problem is the interface. That function can return different styles depending on data that is being passed to useStyles. If we don't create a new rule for each component instance but reuse an existing one, we run the risk of having a specificity issue, because an existing one  was created earlier and specificity when combining with other classes was different than specificity we can get when passing new data and generating a new rule.


Example

State 0

```css
.dynamicContainer-0-0-1 {
  color: green;
}
.override {
  color: red;
}
```
```html
<div class="dynamicContainer-0-0-1 override"/>
```

Resulting color is `red`

Stage 1

We are updating data, now container generates a new rule

```css
.dynamicContainer-0-0-1 {
  color: green;
}
.override {
  color: red;
}
.dynamicContainer-0-0-2 {
  color: blue;
}
```
```html
<div class="dynamicContainer-0-0-2 override"/>
```

Resulting color is `blue`

Its a challenging problem.

**Comment by kof** [comment] 2021-05-14 18:07
Alternatively we could invent a way to control the classes composition. Make sure its done by abstraction that is aware of the specificity we have and it's potential changes. Something that manages composition.

**Comment by IIIristraM** [comment] 2021-05-14 21:24
The point is to create new classes only when content changed, in example above - when color changed. That's how for example `styled-components` works

```jsx
const StyledBox = styled.div`
  display: ${props => props.display};
`

const StyledComponents = () => {
  return (
    <div>
       {Array.from({length: 5}).map((v, i) => (
          <StyledBox display="flex" key={i}>{i}</StyledBox>
        ))}
       <StyledBox display="block" >xxx</StyledBox>
    </div>
  )
}
```

![image](https://user-images.githubusercontent.com/2033959/118332881-6fd26e80-b513-11eb-943a-3bc4fdc2f6ad.png)
two classes created

In case of `jss` it will be six different classes despite the fact that five of them have the same content

**Comment by kof** [comment] 2021-05-15 10:19
Yeah the way Styled Components and emotion are solving it by generating new rules on each update, which creates an infinite amount of CSS rules.

https://codesandbox.io/s/rendering-emotion-vs-styled-components-vs-jss-po0w7

**Comment by IIIristraM** [comment] 2021-05-15 11:03
Well, infinite amount of UI states is extraordinary situation, maybe some real-time graphics, this case probably requires entirely different approach and stack anyway. Usually each UI element has a very few states, and duplication of some rules is not critical at all, and it is easily could be solved by moving dynamic rules in a separate class.

On the other hand, tables, lists, news feeds and image galleries with infinite scroll are common scenarios in a wide range of applications, and thats where we have an infinite amount of CSS rules generated by JSS for every instance of UI element

**Comment by soul-codes** [comment] 2021-05-15 12:25
The crux of the issue IMO appears to be this question: should there by one CSS class per component, or one CSS class per styling state?

As I have noted [above](https://github.com/cssinjs/jss/issues/1181#issuecomment-760022480), one CSS class per component is clearly not tenable if you have many components using the same rule and they are all in the same state.

One CSS class per styling state is presumably how Styled Components and Emotion does it. If care is taken that the class' rule is eventually disposed of when it is no longer needed (the component no longer uses that particular style, or is unmounted), then we would not have an infinite amount of CSS rules. Rather, we would have as many CSS rules as there are _stylistically distinct states_ across all active UI elements using any particular JSS rule. UI elements and their states have a lifecycle. In the context of React components, tapping into this lifecycle is easy with hooks or old-fashioned class callbacks. 

Essentially, two things would happen to make this work:
1. A hash digest is computed for a CSS rule. The hash string is then taken to represent a distinct CSS rule.
2. A register of hashes and the list of components that are in the state where the corresponding style represented by hash is in use.

Now, this is arguably less efficient than _mutating_ a CSS rule when the underlying single component it uses changes its stylistic state. But it makes the case of handling multiple components using the same dynamic JSS rule much more straightforward to reason about.

Since I [last](https://github.com/cssinjs/jss/issues/1181#issuecomment-760022480) commented on this issue, I went on to experiment with this idea, which resulted in [`react-tss`](https://gitlab.com/soul-codes/react-tss/-/blob/master/src/lib/index.ts). It works OK, but I'd very much rather see the functionality working on this repository which already has an active community rather than going alone, so I'd be thrilled to see if the same idea would be implemented here.

The worst case performance situation would be if you were to use a JSS rule to create a JS-driven CSS animation. In this case, new CSS rules would be created (and destroyed) at every animation frame, which is probably (is it?) much less efficient than having one CSS rule for each component that simply mutates. [Disclaimer, braindumping follows:] But I think this could probably be solved easily by exposing an API where the developer can mark certain CSS attributes as "hot", and then either the CSS is applied as a `style` HTML attribute, or a component-specific class is created only in this case. The latter is probably preferable because it preserves the aspect of the API that the styling class(es) alone would be sufficient to style the element.

**Comment by kof** [comment] 2021-05-15 19:23
I do agree that having a list of components with the same css properties coming from function rules is a VERY important use case.

I am just sceptical of the path SC and emotion have chosen, because sometimes you do have many states. A button may very well result in dozens and I think this approach damages the perception of css-in-js, as some call it a "black hole" already.

What other options do we have, let's brainstorm.

**Comment by soul-codes** [comment] 2021-05-16 00:36
> as some call it a "black hole" already.

Can you elaborate more on this? Understanding the community concern in full would help the brainstorming process especially if we want to look into alternatives.

**Comment by kof** [comment] 2021-05-16 08:56
It refers to the fact that you can unknowingly render many more CSS rules than you would expect. That is one of the reasons I am trying to update the dynamic rule when values change, not create a new one including all rules which are part of the composition. This is definitely something one doesn't expect coming from regular CSS.

**Comment by kof** [comment] 2021-05-16 09:58
Right now we have a similar problem though, with the difference that the amount of CSS with dynamic values grows with the amount of instances/elements, not with the amount of variants. Also we don't duplicate static rules between instances, only the dynamic once.

**Comment by kof** [comment] 2021-05-16 11:45
Here is a more concrete example with the specificity problem I mentioned above: https://codesandbox.io/s/react-jss-playground-forked-dr1gi

Right now this works, but if we start reusing the rule "two" between instances, it's source order specificity will be lower than "one" of the second instance, because second instance will render after the first one and it's rule two will stay the same, so we would reuse it, while rule one would change, so we would create a new one.

**Comment by kof** [comment] 2021-05-16 11:55
What we lack right now is the knowledge that those 2 rules where composed on one element. If we knew this, we could duplicate both of them if one of them changes and won't have a dynamic specificity issue, while when they are not composed and don't change, we could reuse them across all instances.

**Comment by kof** [comment] 2021-05-16 13:51
One idea here that would allow us this optimization while still preventing the source order specificity issues is to compose from JSS, using jss-plugin-compose: 

```js
const useStyles = createUseStyles(
  {
    // Dynamic
    one: ({ color }) => ({
      color
    }),
    // Static
    two: () => ({
      composes: '$one',
      color: "green"
    })
  }
);

<div className={classes.two}>{children}</div>;
```

Right now composes doesn't fully work with function rules, but this is essentially a bug or a missing implementation because of lack of time.

**Comment by namnm** [comment] 2021-07-28 11:40
This bug is still happening, please re-open the issue.

**Comment by axelmarciano** [comment] 2022-01-07 23:01
Still happening
