### ISSUE TITLE
Exposing a way to clone a `StyleSheet` instance

### ISSUE THREAD

**Issue by NMinhNguyen** [cssinjs/jss#940] opened 2018-12-19 10:16 UTC
__Is your feature request related to a problem? Please describe.__
This would benefit use cases such as rendering multiple instances of the same Custom Element (where each instance has its own shadow root and you can't use styles from outside the shadow root) whilst only generating styles once and then simply re-injecting them into different insertion points (one per shadow root).

Related to https://github.com/cssinjs/react-jss/issues/297.

__Describe the solution you'd like__
I'm not sure what the best solution would be, but this potentially could be achieved via caching `sheet.toString()` or `sheet.renderer.element.cloneNode()` somehow.

I have a repro with 1000 instances of [Material-UI Button](https://material-ui.com/demos/buttons/) component wrapped in a Custom Element here: https://codesandbox.io/s/5vx8yoooyx. You can see that displaying 1000 buttons is somewhat sluggish, and I believe it is to do with there being a lot of JSS work being redone for each button.

__Are you willing to implement it?__
Yes.

**Comment by kof** [comment] 2018-12-19 12:06
## Questions

- does browser optimize somehow same style rendering inside of shadow root?
- how to implement it with dynamic values where react-jss uses 2 style sheets for static and dynamic value? It seems like it will require basically a special mode that will not separate dynamic from static and use it all as dynamic and so separate instance for each element.
- how do we make it convenient to use it with the shadow root?

**Comment by josgraha** [comment] 2018-12-19 15:48
@kof I'm wondering what you mean by 2 style sheets for static and dynamic value?
Is there a link to some test cases on this?

**Comment by kof** [comment] 2018-12-19 16:13
Make sure to watch this https://github.com/WICG/construct-stylesheets it will fix the problem of sharing styles across shadow roots

**Comment by kof** [comment] 2018-12-19 16:15
and this https://www.w3.org/TR/css-shadow-parts-1/

**Comment by oliviertassinari** [comment] 2018-12-29 14:53
@NMinhNguyen Your test case is interesting because it shows the limitation of using style functions we have with today implementations. At some point, I was investigating whether or not we could have the Material-UI core components uses the @material-ui/system style functions directly (providing the `<Button mx={[1, 2]} />`, etc. APIs). What I benchmarked is the the SSR performance: was going
- from `ButtonBase x 40,724 ops/sec ±1.58% (189 runs sampled)`
-
  - non null styles:  `ButtonBase x 8,780 ops/sec ±2.62% (186 runs sampled)`
  - null style function: `ButtonBase x 15,371 ops/sec ±3.06% (183 runs sampled)`

**Comment by oliviertassinari** [comment] 2018-12-31 15:12
@kof The issue is about the performance implication of attaching a new style sheet for each component instance, something we do with dynamic style sheets. It's not something we do with static style sheets, at the exception of when using a shadow DOM.

**Comment by Jack-Works** [comment] 2019-04-16 08:33
Supports `adoptedStyleSheets`?
This can avoid inset dom node but still get styled

**Comment by kof** [comment] 2019-04-17 14:32
@Jack-Works I will have a look once we start actively looking to support constructible stylee e sheets, feel free to reference it in #968

**Comment by Jack-Works** [comment] 2019-05-25 08:35
@kof Hello any progress on ShadowRoot support?
I changed so many things from `DomRenderer` to create `ConstructableStylesheetsRenderer`, so it feels pain to patching newer codes from `DomRenderer` to `ConstructableStylesheetsRenderer`.
(I'm upgrading @material-ui/* from 3.* to 4.0 which upgrades JSS from 9 to 10 so I also need to update  `ConstructableStylesheetsRenderer` to match JSS 10 to make it work on my project)

**Comment by Jack-Works** [comment] 2019-05-25 13:14
Ok I've done it. `ConstructableStylesheetsRenderer` now matches JSS 10

https://github.com/DimensionDev/Maskbook/commit/e865996f3074b08e5bc5b655e0aba656f48ff3df

**Comment by trusktr** [comment] 2019-10-10 07:20
> styles to `adoptedStyleSheets` instead of `<style>` tag.

Maybe the simplest most naive way, is to monkey patch the `adoptedStyleSheets` property with a getter/setter, and ensure that it always includes all the JSS style sheets in the array?

**Comment by Jack-Works** [comment] 2019-10-19 06:47
I'm doing it in this way:

1. Change the `getHead` function. Let JSS inject the `<style>` into a fake head element.
2. Hook all the functions on the DomRenderer. After the method get called, collect the current `<style>`s in the fake head element.
3. Transform them into the `CSSStyleSheet` object then apply them to all of my `ShadowRoot`s

**Comment by kof** [comment] 2021-01-27 12:38
Closing this for now, since no-one is actively working on it. We also optimized the behavior along the way and reuse a style sheet for both static and dynamic styles

**Closed by kof** 2021-01-27 12:38 UTC
