### ISSUE TITLE
Dynamic Global styles are not created

### ISSUE THREAD

**Issue by jackrussell1996** [cssinjs/jss#1417] opened 2020-11-02 21:24 UTC
__Expected behavior:__
I am able to create dynamic global styles with react-jss

__Describe the bug:__
I am able to create dynamic styles with react-jss
I am able to create global styles with react-jss
I am not able to create dynamic global styles with react-jss

`Warning: [JSS] Unknown rule @global-d0`

__Codesandbox link:__ 
https://codesandbox.io/s/react-jss-global-dynamic-tm1xc

__Versions (please complete the following information):__
 - jss: 10.4.0
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: macOS
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by sam-m-m** [comment] 2020-12-02 20:25
I have the exact same issue. It works with `jss` as mentioned in this [comment](https://github.com/cssinjs/jss/issues/682#issuecomment-542895330) but not with `react-jss`.

**Comment by kof** [comment] 2021-01-27 12:21
seems like a duplicate of https://github.com/cssinjs/jss/issues/1335

**Closed by kof** 2021-01-27 12:21 UTC
